### ISSUE TITLE
not work!

### ISSUE THREAD

**Issue by pws2016** [TomSeldon/StubHub#3]
Hello,
how i install your script without composer and how working?

**Comment by TomSeldon** [comment]
Hi @pws2016, unfortunately, as per the notice in the readme, this isn't under active development or maintenance, and was written 5 years ago. I have no idea if this still works with the StubHub API, which may have changed drastically since this was written. 

In fact, the API docs linked to from the readme (http://stubhubapi.stubhub.com/) no longer even work.

I've just taken a brief look at the new StubHub API docs, and it seems things have changed and you now require an account (and probably an API key or similar) in order to access the API, whereas when I first wrote this it was completely open. There may be more drastic changes, too.

I'd suggest either looking for an actively maintained alternative to this project, or if there simply aren't any, then your only option may be to roll your own or to update this project. If the latter, I'll gladly look at any pull requests, but I'm afraid I won't be able to develop this further myself.
